version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gestao-projetos-db
    restart: always
    environment:
      POSTGRES_DB: gestao_projetos
      POSTGRES_USER: user_gestao
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: gestao-projetos-keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/gestao_projetos?currentSchema=keycloak
      KC_DB_USERNAME: user_gestao
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
