version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gestao-projetos-db
    restart: always
    environment:
      POSTGRES_DB: gestao_projetos
      POSTGRES_USER: user_gestao
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
