spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_projetos
    username: user_gestao
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always