spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_projetos
    username: user_gestao
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: gestao_system

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/gestao-projetos
          jwk-set-uri: http://localhost:9090/realms/gestao-projetos/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:9090
  realm: gestao-projetos
  resource: gestao-projetos-backend
  bearer-only: true
  credentials:
    secret: bkHoIcm1xm0oRhyf8LYQ9WJIVkqhwTob
  use-resource-role-mappings: true
